//
//  ExpectedOutput.swift
//  AIParsingTestKit
//
//  Protocol defining the expected output structure and comparison logic.
//

import Foundation
import FoundationModels

/// A value type that can represent different kinds of metric values.
///
/// This enum supports boolean, numeric, and string metrics for flexible
/// comparison results.
public enum MetricValue: Sendable, Equatable {
    case boolean(Bool)
    case double(Double)
    case integer(Int)
    case string(String)
    case optionalInteger(Int?)
    case optionalDouble(Double?)

    /// Converts the metric value to a string suitable for CSV export.
    public var csvString: String {
        switch self {
        case .boolean(let value):
            return "\(value)"
        case .double(let value):
            return String(format: "%.2f", value)
        case .integer(let value):
            return "\(value)"
        case .string(let value):
            return value
        case .optionalInteger(let value):
            return value.map { "\($0)" } ?? ""
        case .optionalDouble(let value):
            return value.map { String(format: "%.2f", $0) } ?? ""
        }
    }

    /// Returns the boolean value if this is a boolean metric.
    public var boolValue: Bool? {
        if case .boolean(let value) = self {
            return value
        }
        return nil
    }

    /// Returns the double value if this is a numeric metric.
    public var doubleValue: Double? {
        switch self {
        case .double(let value):
            return value
        case .integer(let value):
            return Double(value)
        case .optionalDouble(let value):
            return value
        case .optionalInteger(let value):
            return value.map { Double($0) }
        default:
            return nil
        }
    }
}

/// A protocol defining the expected output structure for LLM evaluation.
///
/// The expected output knows:
/// - What actual output type to expect from the LLM (must be `@Generable`)
/// - How to compare the actual output against expected values
/// - What minimum confidence threshold is acceptable
///
/// Example:
/// ```swift
/// struct MyExpectedOutput: ExpectedOutput {
///     typealias ActualOutput = MyGenerableType
///
///     let expectedCategory: String
///     let minimumConfidence: Double = 0.7
///
///     func compare(to actual: MyGenerableType) -> [String: MetricValue] {
///         return [
///             "category_correct": .boolean(actual.category == expectedCategory),
///             "confidence": .double(actual.confidence)
///         ]
///     }
/// }
/// ```
public protocol ExpectedOutput: Sendable {
    /// The type that the LLM will generate. Must conform to `Generable`.
    associatedtype ActualOutput: Generable & Sendable

    /// Compares the actual LLM output to this expected output.
    ///
    /// - Parameter actual: The output generated by the LLM.
    /// - Returns: A dictionary of metric names to their computed values.
    func compare(to actual: ActualOutput) -> [String: MetricValue]

    /// The minimum confidence score required for the result to be considered calibrated.
    var minimumConfidence: Double { get }
}
